export const LOAD_USERS_PENDING = "LOAD_USERS_PENDING";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const DEL_PRODUCT_CART = "DEL_PRODUCT_CART";

export const FETCH_WISH_PENDING = "FETCH_WISH_PENDING";
export const FETCH_WISH_SUCCESS = "FETCH_WISH_SUCCESS";
export const FETCH_WISH_ERROR = "FETCH_WISH_ERROR";

export const FETCH_CART_PENDING = "FETCH_CART_PENDING";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";
